version: '3.8'

services:
  marvin-blogger:
    container_name: marvin-blogger
    build: .
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    extra_hosts:
      - "qdrant.marvn.club:172.236.2.45"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
